version: "3"
services:
  data-prepper:
    container_name: data-prepper
    image: opensearchproject/data-prepper:latest
    volumes:
      - ./pipeline.yaml:/usr/share/data-prepper/pipelines/pipeline.yaml
    ports:
      - "4900:4900"
    networks:
      - opensearch-net

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    depends_on:
      - data-prepper
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /home/shuraim/monkeytilt/java/crypto_games/gateway/logs/myApp.log:/var/log/gateway.log
      - /home/shuraim/monkeytilt/java/crypto_games/clusterservice/logs/myApp.log:/var/log/cluster.log
      - /home/shuraim/monkeytilt/java/crypto_games/hedger-client/logs/myApp.log:/var/log/hedger.log
      - ./test2.log:/var/log/test2.log
      - ./filter.lua:/fluent-bit/etc/filter.lua
      - /home/alpha/fluent-bit/storage:/var/log/flb-storage

    environment:
      FLB_STORAGE_PATH: "/var/log/flb-storage"
      FLB_TAIL_BUFFER_CHUNK_SIZE: "512KB"
      FLB_TAIL_BUFFER_MAX_SIZE: "5MB"
      FLB_STORAGE_MAX_CHUNKS_UP: "10"
      FLB_STORAGE_BACKLOG_MEM_LIMIT: "50MB"
    networks:
      - opensearch-net

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch
    networks:
      - opensearch-net

networks:
  opensearch-net:
