gateway_pipeline:
  source:
    http:
      ssl: false
      port: 2021
  processor:
    - grok:
        match:
          log: ["%{COMMONAPACHELOG}"]
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: admin
        password: admin
        index: gateway_logs
hedger_pipeline:
  source:
    http:
      ssl: false
      port: 2022
  processor:
    - grok:
        match:
          log: ["%{COMMONAPACHELOG}"]
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: admin
        password: admin
        index: hedger_logs
cluster_pipeline:
  source:
    http:
      ssl: false
      port: 2023
  processor:
    - grok:
        match:
          log: ["%{COMMONAPACHELOG}"]
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: admin
        password: admin
        index: cluster_logs